### ISSUE TITLE
Current Stages doesn't mark "isComplete" in Realm database

### ISSUE THREAD

**Issue by riko105** [andrewwoz/Fifa-Tournament-Generator#6]
I have noticed a bug:
When all matches in certain stage is completed - it isn't mark as "isCompleted" in Realm Browser 

![screen shot 2016-11-27 at 13 44 46](https://cloud.githubusercontent.com/assets/10188785/20648241/2f6e73de-b4aa-11e6-905e-3380224b8436.jpg)

**Comment by riko105** [comment]
So, now realm db model works correctly
![screen shot 2016-11-27 at 15 10 10](https://cloud.githubusercontent.com/assets/10188785/20648578/c0053992-b4b3-11e6-919d-16e2003659a5.jpg)

**Comment by andrewwoz** [comment]
Describe problem more detailed please

**Comment by riko105** [comment]
Now good?

**Comment by andrewwoz** [comment]
Great. Good job mate
